create table public.sponsoreds (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  details json null,
  image text null,
  links json null,
  status text null default '''Inactive''::text'::text,
  constraint sponsoreds_pkey primary key (id)
) TABLESPACE pg_default;




create table public.news (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  name text null,
  image text null,
  content text null,
  type text null,
  link text null,
  constraint news_pkey primary key (id)
) TABLESPACE pg_default;



create table public.events (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  name text null,
  venue text null,
  image text null,
  description text null,
  date date null,
  time text null,
  constraint events_pkey primary key (id)
) TABLESPACE pg_default;







create table public.blogs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  content text null,
  image text null,
  author text null,
  date date null,
  constraint blogs_pkey primary key (id)
) TABLESPACE pg_default;


create table public.team_members (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  name text null,
  designation text null,
  quote text null,
  image text null,
  status text null default 'active',
  order_index integer null,
  constraint team_members_pkey primary key (id)
) TABLESPACE pg_default;